import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import { useSignMessage, useWriteContract } from 'wagmi';
import { signMessage , signTypedData } from '@wagmi/core'
import  constants from '../../abi.json'
import { config } from '../wagmi';

const Home: NextPage = () => {
  const [vote, setVote] = useState<boolean | null>(null);
  const [signature, setSignature] = useState<string | null>(null);
  const { writeContractAsync } = useWriteContract();

  // Hook para firmar mensajes con wagmi
  const { signMessageAsync } = useSignMessage();

  const handleVote = async (userVote: boolean) => {
    setVote(userVote);
    const data = await signMessageAsync({message:'Yes'});
    console.log(data as `0x${string}`);
    // Crear el mensaje JSON
    // const message = JSON.stringify({ vote: userVote ? 'yes' : 'no' });

    // Firmar el mensaje
    // try {
    //   // const signature = await signMessage(config, { message });
    //   const signature = await signMessageAsync({})
    //   console.log('El usuario firmo: ' + signature as `x0${string}`)
    //   setSignature(signature  as `x0${string}`);
    // } catch (error) {
    //   console.error('Error al firmar el mensaje:', error);
    // }
  };

  // Llamar a la función del contrato después de que la firma sea exitosa
  const submitVote = async () => {
    if (signature && vote !== null) {
      try {
        const hashTrs = await writeContractAsync({ 
          abi: constants.abi,
          address: constants.address as `0x${string}`,
          functionName: 'vote',
          args: [
            vote,
            signature
          ],
       })
        console.log('Voto enviado con éxito: ' + hashTrs);
      } catch (error) {
        console.error('Error al enviar el voto:', error);
      }
    }
  };
  
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <h1>Votación en Blockchain</h1>
        <button onClick={() => handleVote(true)}>Votar Sí</button>
        <button onClick={() => handleVote(false)}>Votar No</button>
        <button onClick={submitVote} disabled={!signature}>
          Enviar Voto
        </button>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;

